service: aws-node-project

frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs14.x
  environment:
    DB_HOST: workos.cclfxume2xkm.us-east-1.rds.amazonaws.com
    DB_NAME: slack
    DB_USER: admin
    DB_PASSWORD: ${ssm:/workos/db-password}

functions:
  webhook:
    handler: src/handlers/webhook.handler
    environment:
      QUEUE_URL: ${construct:user-event.queueUrl}
    events:
      - http:
          path: webhook
          method: post
          cors: true
  ui:
    handler: src/handlers/ui.handler
    events:
      - http:
          path: /
          method: get
          cors: true
  create_groups:
    handler: src/handlers/group.handler
    events:
      - http:
          path: group
          method: post
          cors: true

constructs:
  user-event:
    type: queue
    worker:
      handler: src/handlers/user-updater.handler

package:
  patterns:
    - "!tests/**"

plugins:
  - serverless-plugin-typescript
  - serverless-lift
  - serverless-offline
