service: slack-user-tool

frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs14.x
  environment:
    DDB_USER: ${self:custom.ddbUser}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
      Resource: "arn:aws:dynamodb:${self:custom.region}:*:table/${self:custom.stage}-*"

custom:
  stage: ${opt:stage, 'dev'}
  region: ${opt:region, 'us-east-1'}
  ddbUser: ${self:custom.stage}-user

functions:
  webhook:
    handler: src/handlers/webhook.handler
    environment:
      QUEUE_URL: ${construct:user-event.queueUrl}
    events:
      - http:
          path: webhook
          method: post
          cors: true
  ui:
    handler: src/handlers/ui.handler
    events:
      - http:
          path: /
          method: get
          cors: true

constructs:
  user-event:
    type: queue
    worker:
      handler: src/handlers/user-updater.handler

resources:
  Resources:
    UserTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:custom.ddbUser}
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        PointInTimeRecoverySpecification:
          PointInTimeRecoveryEnabled: true

package:
  patterns:
    - "!tests/**"

plugins:
  - serverless-plugin-typescript
  - serverless-lift
  - serverless-offline
